In [1]:
#Stochastic gradient descend

In [331]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from scipy.stats import norm
from sklearn import preprocessing
from random import random
import matplotlib.pyplot as plt


from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [332]:
df = pd.read_csv("C:/Users/ilan/Documents/GitHub/MaterialyTareas/datos/regLinPoli.csv")

In [333]:
df.describe()

X           X2           X3           X4           X5  \
count  1029.000000  1029.000000  1029.000000  1029.000000  1029.000000   
mean     48.052380  3113.669342     1.542203    -0.011250   628.000000   
std      28.379936  2891.956247     0.452374     0.717016   297.191016   
min       0.006314     0.000040    -2.199666    -0.999993   114.000000   
25%      23.174764   537.069692     1.365015    -0.731530   371.000000   
50%      47.655827  2271.077831     1.678116    -0.046938   628.000000   
75%      71.372550  5094.040864     1.853531     0.732296   885.000000   
max      99.873062  9974.628611     1.999448     1.000000  1142.000000   

                  y  
count   1029.000000  
mean    3113.490528  
std     2892.963581  
min        0.000040  
25%      522.757565  
50%     2262.728789  
75%     5093.260718  
max    10028.067820

In [368]:
# Here df.columns i# Separate both train and test as well as the response variable
#X_train=np.array(df[df.columns[0:-1]])[index==1]
#X_test=np.array(df[df.columns[0:-1]])[index==0]
#Y_train=np.array(df[df.columns[-1]])[index==1]
#Y_test=np.array(df[df.columns[-1]])[index==0] 
# a list of all the columns and df.columns[0:-1] is all columns minus the last which is y. 
# If the data had headers you could use column names: df[['column1','column2','etc']]
X_train, X_test, Y_train, Y_test = train_test_split(df[df.columns[0:-1]],df[[df.columns[-1]]], train_size=0.75)

In [369]:
# index for selecting data 0.75 is the percentage in training
index=np.array([1 if random() < 0.75 else 0 for i in range(len(df))])

In [370]:
# Separate both train and test as well as the response variable
X_train=np.asarray(X_train)
X_test=np.asarray(X_test)
Y_train=np.asarray(Y_train)
Y_test=np.asarray(Y_test)

In [371]:
# Normalizar no ayuda mucho pero sale igual al de sklearn. Para que las alturas del pdf signifiquen lo mismo 
#scaler = preprocessing.StandardScaler().fit(X_train)
#X_train=scaler.transform(X_train)
#X_test=scaler.transform(X_test)

from sklearn import preprocessing
scaleX=preprocessing.StandardScaler()
scaleY=preprocessing.StandardScaler()

scaleX.fit(X_train)
X_train=scaleX.transform(X_train)
X_test=scaleX.transform(X_test)

scaleY.fit(Y_train)
Y_train=scaleY.transform(Y_train)
Y_test=scaleY.transform(Y_test)



In [372]:
numrows=len(X_train)
numcols=len(X_train[0])

w=np.ones(numcols+1)
a=np.array(X_train[0])
x=[1]
x=np.concatenate((x,a), axis=0)
print(x)

[ 1.          0.19607092 -0.08257016  0.41246405  0.02386024 -1.55061793]


In [401]:
#Iterativo normal
w=np.ones(numcols+1)
print(w)
lam=0.00
for j in range(0,9):

    for i in range(0, (numrows-1)):
        a=np.array(X_train[i])
        x=[1]
        #print(x)
        x=np.concatenate((x,a), axis=0)
        #print(x)
        v=np.dot(w,x)
        #print(v)
        #print(f)
        aux=w[0]
        w=w+.01*((Y_train[i]-v))*x-lam*w
        #print(w)
        w[0]=w[0]+lam*aux
 


[ 1.  1.  1.  1.  1.  1.]


In [402]:
print(w)

[-0.00239822  0.3313467   0.76009884 -0.10737539 -0.00919409  0.00381365]


In [403]:
numrows=len(X_test)
Y_error= []
for i in range(0, (numrows)):
    a=np.array(X_test[i])
    x=[1]
    x=np.concatenate((x,a), axis=0)
    Y_error.append(np.dot(w,x))

    

error= mean_squared_error(Y_test, Y_error)
print(error)

0.00221643448303


In [395]:
#Minibatch

numrows=len(X_train)
numcols=len(X_train[0])
numBadge=50

w=np.ones(numcols+1)
print(w)
lam=0.001
for j in range(0,(numrows)*4):
    
    randomSample=np.random.choice(numrows-1, numBadge)
    vv=[]
    xx=np.zeros(numcols+1)
    for i in randomSample:
        a=np.array(X_train[i])
        x=[1]
        x=np.concatenate((x,a), axis=0)
        vv.append(np.dot(w,x))
        xx=xx+x
    
    #print(v)
    #print(f)
    x=xx/numBadge
    v=np.mean(vv)
    aux=w[0]
    w=w+.01*((Y_train[i]-v))*x-lam*w
    #print(w)
    w[0]=w[0]+lam*aux
 

[ 1.  1.  1.  1.  1.  1.]


In [396]:
print(w)

[-0.07427658  0.10537323  0.11612419  0.07995737  0.02434805 -0.01444749]


In [397]:
numrows=len(X_test)
Y_error= []
for i in range(0, (numrows)):
    a=np.array(X_test[i])
    x=[1]
    x=np.concatenate((x,a), axis=0)
    Y_error.append(np.dot(w,x))

    

error= mean_squared_error(Y_test, Y_error)
print(error)

0.562942200308
